Maturita.Web/Areas/Programovani/Controllers/AlgorithmsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Programovani.Controllers
{
    [Area("Programovani")]
    public class AlgorithmsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BubbleSort()
        {
            return View();
        }

        public IActionResult SelectionSort()
        {
            return View();
        }

        public IActionResult InsertionSort()
        {
            return View();
        }

        public IActionResult QuickSort()
        {
            return View();
        }

        public IActionResult MergeSort()
        {
            return View();
        }

        public IActionResult HeapSort()
        {
            return View();
        }
    }
}

Maturita.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-VD765VFTKL"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-VD765VFTKL');
    </script>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>

    <link rel="icon" type="image/png" href="~/WebIcon.ico" sizes="64x64">

    @* Boostrap *@
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css"/>

    @* Custom CSS *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Sort/MainSort.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/NavBar.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/ScrollBar.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Spacers.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Scroll.css" asp-append-version="true"/>

    @* Highlight.js *@
    <link rel="stylesheet" href="~/lib/highlight.js/styles/atom-one-dark.min.css">

    @* Video.js *@
    <link rel="stylesheet" href="~/lib/video.js/video-js.min.css"/>
    <link rel="stylesheet" href="~/css/YoutubeVideo.css"/>

    @await RenderSectionAsync("Styles", required: false)


</head>
<body>
    <partial name="_NavBar"/>
    
    <div onclick="location.href = '/video'" id="ShowMore"></div>

    <div class="container">
        <main role="main" class="pb-3">
            @if (!string.IsNullOrEmpty(ViewBag.Category))
            {
                <div class="mini-header">@Html.Raw(ViewBag.Category)</div>
            }
            @RenderBody()
        </main>
        @if (ViewData["Author"] != null)
        {
            <div class="writer text-center">Napsal: <span class="text-primary">@ViewData["Author"]</span></div>
        }
        @if (ViewData["Editor"] != null)
        {
            <div class="writer text-center">Upravil: <span class="text-primary">@ViewData["Editor"]</span></div>
        }
    </div>
    <a href="#" id="GoUp" class="go-up go-up-notActive"><i class="bi bi-chevron-up"></i></a>

    <div class="spacer down-spacer"></div>

    @* Jquery *@
    <script src="~/lib/jquery/jquery.min.js"></script>

    @* Boostrap *@
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    @* Video.js *@
    <script src="~/lib/video.js/video.min.js"></script>

    <script src="~/lib/highlight.js/highlight.min.js"></script>


    @* Highlight.js *@
    <script>hljs.highlightAll();</script>


    @* Custom JS *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/ScrollAnimate.js" asp-append-version="true"></script>
    @if (ViewBag.GenerateContent == true)
    {
        <script src="~/js/ContentWriter.js" asp-append-version="true"></script>
    }
    @await RenderSectionAsync("Scripts", required: false)
    
    <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="Jbohacek" data-description="Support me on Buy me a coffee!" data-message="Ahoj, pracuji na tomto webu už čtyři měsíce. Byl bych moc vděčný za příspěvek. Děkuji! 💖" data-color="#5F7FFF" data-position="Right" data-x_margin="18" data-y_margin="18"></script>

    </body>
</html>

Maturita.Web/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm box-shadow">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav text-white w-100">
                    <a class="nav-link text-white fw-bold fs-3 nav-my-logo d-lg-block d-none" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/Pictures/Logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                        Maturita Help
                    </a>
                    
                    <div class="d-xl-flex d-block ms-sm-auto me-sm-auto justify-content-around ">
                        <a class="nav-link text-white fw-bold fs-3 nav-my-logo d-lg-none d-block" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/Pictures/Logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                            Maturita Help
                        </a>

                        <a class="nav-link nav-my-item" asp-area="Programovani" asp-controller="Home" asp-action="Index"><i class="bi bi-code-slash"></i> Programování</a>
                        <a class="nav-link nav-my-item" asp-area="Database" asp-controller="Home" asp-action="Index"><i class="bi bi-database"></i> Databáze</a>
                        <a class="nav-link nav-my-item" asp-area="ProgramoveVybaveni" asp-controller="Home" asp-action="Index"><i class="bi bi-pc-display"></i> Programové vybavení</a>
                        <a class="nav-link nav-my-item" asp-area="Cestina" asp-controller="Home" asp-action="Index"><i class="bi bi-book"></i> Čeština</a>
                        <hr class="d-xl-none"/>
                        <a class="nav-link nav-my-item d-xl-none " href="https://app.loopedin.io/maturita-web#/roadmap"><i class="bi bi-map"></i> Roadmap</a>
                        <a class="nav-link nav-my-item d-xl-none " asp-area="" asp-controller="Home" asp-action="Contact"><i class="bi bi-box-arrow-up-left"></i> Kontakt</a>
                    </div>

                </ul>
                <ul class="navbar-nav text-center d-xl-flex d-none " style="width: 15vw">
                    <a class="nav-link" href="https://app.loopedin.io/maturita-web#/roadmap"><i class="bi bi-map"></i> Roadmap</a>
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact"><i class="bi bi-box-arrow-up-left"></i> Kontakt</a>

                </ul>
            </div>
        </div>
    </nav>
</header>

@if (!string.IsNullOrEmpty(ViewBag.Waves))
{
    @Html.Raw($"<div class=\"spacer {ViewBag.Waves}-spacer hidden-spacer\"></div>")
}
else
{
    <div class="spacer main-spacer hidden-spacer"></div>
}




@*                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Sort Methody
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Sort" asp-action="Index">Vysvětlení</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="BubbleSort">Bubble Sort</a></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="SelectionSort">SelectionSort</a></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="InsertionSort">InsertionSort</a></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="QuickSort">QuickSort</a></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="MergeSort">MergeSort</a></li>
                            <li><a class="dropdown-item" asp-area="Programovani" asp-controller="Algorithms" asp-action="HeapSort">HeapSort</a></li>
                        </ul>
                    </li> *@

Maturita.Web/Views/Shared/_RedirectSite.cshtml
@model RedirectModel


@{
    Layout = "_Layout"; // Nechat jak je

    ViewBag.Title = "Přesměrování";

}

<div class="display-1">
    Přesměrování
</div>


<div class="background-text text-center">
    <div class="text-center display-3">Informace jsou na jiné webové stánce</div>
    <a class="" href="@Model.Url">@Model.Url</a>
</div>

Maturita.Web/Views/Shared/_Sources.cshtml
@model SourcesModel

<div class="background-text p-3 fs-5 mt-5">
    Zdroje:
    <ul>
        @foreach (string link in Model.GetLinks())
        {
            @if (!link.Contains("https"))
            {
                <li style="word-break: break-all; list-style-type: none">
                    <br />@link
                </li>
            }
            else
            {
                <li style="word-break: break-all">
                    <a href="@link">@link</a>
                </li>
            }

            
        }
    </ul>
</div>

Maturita.Web/Views/Shared/_VideoPlayer.cshtml
@model VideoModel

<video id="my-video"
       class="video-js vjs-fluid"
       controls
       preload="auto"
       data-setup="{}">
    <source src="~/Videos/@Model.Path" type="video/mp4" />
    <source src="MY_VIDEO.webm" type="video/webm" />
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a
        web browser that
        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
</video>

<div class="d-flex justify-content-end">
   <div>Zdroj: <a href="@Model.Link">Video Link</a></div>
</div>

Maturita.Web/Views/Shared/_YoutubeVideoPlayer.cshtml
@model string

<div class="videoWrapper my-3">
    <!-- Copy & Pasted from YouTube -->
    <iframe width="560" height="349" src="@Model" frameborder="0" allowfullscreen></iframe>
</div>