Maturita.Web/Areas/Cestina/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Cestina.Controllers
{
    [Area("Cestina")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PsaniMekkeNeboTvrde()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/Database/Controllers/DatabaseCreateController.cs
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Database.Controllers
{
    [Area("Database")]
    public class DatabaseCreateController : Controller
    {

        public IActionResult Design()
        {
            return View();
        }

        public IActionResult Creation()
        {
            return View();
        }

        
    }
}

Maturita.Web/Areas/Database/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Database.Controllers
{
    [Area("Database")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/Database/Controllers/MsSqlSecurityController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Database.Controllers
{
    [Area("Database")]
    public class MsSqlSecurityController : Controller
    {
        public IActionResult LoginAndUser()
        {
            return View();
        }

        public IActionResult Audit()
        {
            return View();
        }

        public IActionResult Backup()
        {
            return View();
        }

        public IActionResult Encryption()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/Database/Controllers/MssqlController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Database.Controllers
{
    [Area("Database")]
    public class MssqlController : Controller
    {
        public IActionResult Replication()
        {
            return View();
        }

        public IActionResult Mirroring()
        {
            return View();
        }

        public IActionResult Transaction()
        {
            return View();
        }

        public IActionResult Partitioning()
        {
            return View();
        }

        public IActionResult LogShipping()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/Database/Controllers/SqlTablesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Database.Controllers
{
    [Area("Database")]
    public class SqlTablesController : Controller
    {
        public IActionResult Zakladnimodifikacedat()
        {
            return View();
        }

        public IActionResult Selects()
        {
            return View();
        }
        public IActionResult SelectsJoins()
        {
            return View();
        }
        public IActionResult DDL()
        {
            return View();
        }

        public IActionResult Views()
        {
            return View();
        }

        public IActionResult TemporaryTables()
        {
            return View();
        }

        public IActionResult ProcAndFunctions()
        {
            return View();
        }

        public IActionResult Triggers()
        {
            return View();
        }

        public IActionResult Cursors()
        {
            return View();
        }

        public IActionResult TokProgramu()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/Programovani/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.Programovani.Controllers
{
    [Area("Programovani")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Maturita.Web/Areas/ProgramoveVybaveni/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Areas.ProgramoveVybaveni.Controllers
{
    [Area("ProgramoveVybaveni")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Maturita.Web/Controllers/HomeController.cs
using Maturita.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Reflection;
using Maturita.Web.Managers;
using Maturita.Web.Models.Data;
using Maturita.Web.Models.Functional;

namespace Maturita.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            

            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Maturita.Web/Areas/Database/Views/Home/Index.cshtml
@using Maturita.Web.Managers


@{
    ViewBag.Title = "Database";
    Layout = "_Layout";
    ViewBag.Category = "";
}

<h2 class="display-1 mb-4"><i class="bi bi-database"></i> Database</h2>
<div class="d-flex gap-5 flex-md-row flex-column-reverse">
    <div class="h-100 w-100">
        <div class="background-text">
            Zde najdeš všechny okruhy z čeho je maturitní zkoušení a praxe.<br/>
            <code>CTRL + SHIFT + R</code> = resetuje intellsence v mssql studiu
        </div>

        <div class="display-4 hidden">
            Jak si mohu procvičit?
        </div>
        <div class="background-text">
            Stačí udělat <span>všechny projekty</span>, který nalezneš níže a měl bys být připravený na <span>všechno</span>.
            Doporučuju neopoužívat na řešení internet a zkusit si podarit pouze s <span>dokumentací.</span>
        </div>
        
        @await Component.InvokeAsync("ExercisesComponent", new {type = ProjectManager.ProjectType.Dbs})
        
    </div>
    <div class="background-text h-100 w-100">
        <div class="text-danger fs-6 text-center">
            Vytvořeno relativně v krátké době, očekávejte chybky.
        </div>
        <div class="display-4 mb-3">Okruhy</div>
        <div class="ms-3">

            <div style="font-weight: 300; font-size: 26px">Práce s databazí</div>
            <ul>
                <li><a disabled asp-area="Database" asp-controller="DatabaseCreate" asp-action="Design">Návrh databáse a obecné informace</a></li>
                <li><a asp-area="Database" asp-controller="DatabaseCreate" asp-action="Creation">Vytváření databaze</a></li>
            </ul>

            <div style="font-weight: 300; font-size: 26px">Práce s tabulky</div>
            <ul>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="Selects">Dotazy - select</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="Views">Pohledy - views</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="TokProgramu">Tok programu - If,While,Case,Declare,set</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="TemporaryTables">Dočasné tabulky - temporary tables</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="ProcAndFunctions">Procedury a funkce - procedures & functions</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="SelectsJoins">Dotazy Joins - select Joins</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="DDL">DDL - Data Definition Language</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="Zakladnimodifikacedat">DML - Základní modifikace dat</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="Triggers">Triggery - Triggers</a></li>
                <li><a asp-area="Database" asp-controller="SqlTables" asp-action="Cursors">Kurzory - cursors</a></li>
            </ul>

            <div style="font-weight: 300; font-size: 26px">Práce s daty</div>
            <ul>
                <li><a asp-controller="Mssql" asp-action="Transaction">Transactions</a></li>
                <li><a asp-area="Database" asp-controller="SqlDataManipulation" asp-action="ImportExportTextElements">Import data - CSV,Excel,TXT, Access</a></li>
                <li><a asp-controller="SqlDataManipulation" asp-action="ImportExportSsis">Import data - SSIS</a></li>
                <li><a asp-controller="Mssql" asp-action="Partitioning">Dělení dat - Partitioning</a></li>
            </ul>


            <div style="font-weight: 300; font-size: 26px">Zabezpečení serveru/dat</div>
            <ul>
                <li><a asp-controller="MsSqlSecurity" asp-action="Audit">Audit akcí - Audit</a></li>
                <li><a asp-controller="MsSqlSecurity" asp-action="Backup">Zálohování - Backup </a></li>
                <li><a asp-controller="MsSqlSecurity" asp-action="Encryption">Šifrování dat - Encryption</a></li>
                <li><a asp-controller="MsSqlSecurity" asp-action="LoginAndUser">uživatelé a servrové role - Login and User</a></li>
            </ul>

            <div style="font-weight: 300; font-size: 26px">Data mezi servery</div>
            <ul>
                <li><a asp-controller="Mssql" asp-action="LogShipping">Log shipping</a></li>
                <li><a asp-controller="Mssql" asp-action="Replication">Replikace</a></li>
                <li><a asp-controller="Mssql" asp-action="Mirroring">Mirroring</a></li>

            </ul>

        </div>

    </div>

</div>