Maturita.Web/Controllers/RedirectController.cs
using Maturita.Web.Models.Functional;
using Microsoft.AspNetCore.Mvc;

namespace Maturita.Web.Controllers
{
    public class RedirectController : Controller
    {
        public IActionResult Index(string url, string desc, string backUrl)
        {
            RedirectModel redirectModel = new RedirectModel()
            {
                Url = url,
                Description = desc,
                BackUrl = backUrl
            };

            return View("_RedirectSite", redirectModel);
        }
    }
}

Maturita.Web/Views/_Template.cshtml
@* /////////////////////////////////////////// *@
@{
    Layout = "_Layout"; // Nechat jak je

    ViewBag.Title = "[Nadpis stránka]";
    ViewBag.Author = "[Autor]";
    ViewBag.Editor = "[Editor]"; // Pokud není, tak vymazat

    ViewBag.GenerateContent = false; 
    /*
     * false = Negeneruje se obsah
     * true / nic = generuje se obsah
     */
}
<div class="display-1">
    @ViewBag.Title
</div>
@* /////////////////////////////////////////// *@

@* Je potřeba na vygenerování jednoduchého seznamu *@
<div class="display-2">
    Podnadpisz
</div>

@* Tohle vkládat do article *@
<div class="display-3">
    Menší nadpis
</div>

@* Pokud má <a> "disabled" tak se link zneplatní. Stačí smazat a bude fungovat *@

<a asp-controller="Access" asp-action="TabulkyARelace" disabled>Tabulky a relace</a> @* Nefunkční *@
<a asp-controller="Access" asp-action="TabulkyARelace">Tabulky a relace</a> @* Funkční *@


@* Text s pozadím *@
<article>
    <br/> @* Enter *@
    
    <b>Tučně</b> @* tučně *@
    
    <i>Italic</i> @* Italic *@
    
    <u>Underline</u> @* Underline *@
    
    <span>Modrý text</span> @* udělá to modrý text na zvýraznění *@
</article>


@* Text s pozadím  *@
<div class="background-text">
    
    <br/> @* Enter *@
    
    <b>Tučně</b> @* tučně *@
    
    <i>Italic</i> @* Italic *@
    
    <u>Underline</u> @* Underline *@
    
    <span>Modrý text</span> @* udělá to modrý text na zvýraznění *@
</div>


@* 
    Obrazek

Velikost se mění sama, ale muže se ovlivnit třídou, v základu 50

w-100 - 100% šířka
w-75 - 75% šířka
w-50 - 50% šířka
w-25 - 25% šířka 

*@

<img src="~/Pictures/Variables/doplnkovykod.png" class="img-fluid d-block mx-auto w-50">

@* Obrazek s pozadim, kvůli prohlednosti (bg-info)*@
<img src="~/Pictures/Variables/doplnkovykod.png" class="bg-info img-fluid d-block mx-auto w-50">



@* Kod
Pro kod tu je highliht.js, který zvýrazní syntaxi

language-csharp c#
language-sql 
language-html

*@

<pre>
    <code class="language-csharp">

    </code>
</pre>

@* Video
Pro tu je to udělaný partial view, který se jmenuje _VideoPlayer.cshtml

defualtni cesta je /wwwroot/Videos/ a musi to být mp4



*@

@await Html.PartialAsync("_VideoPlayer", new VideoModel("Sorts/BubbleSort.mp4", "https://www.youtube.com/watch?v=xli_FI7CuzA&t=2s"))


@* Při importu z youtube klikněte na tlačítko "Sdílet" a pak "Vložit" a zkopírujte link na video v <iframu> *@
@await Html.PartialAsync("_YoutubeVideoPlayer", "https://www.youtube.com/embed/kKbLDqUJ3gY?si=0Hn66eA6o-KJHAko")


@*       
Zdroje
Pro tu je to udělaný partial view, který se jmenuje _Sources.cshtml

Pomlčka udělá z toho "nadpis".

Nesmí obsahovat http !!!! 

*@

@await Html.PartialAsync("_Sources", 
    new SourcesModel(
        "-Datove typy a velikosti:",
        "https://learn.microsoft.com/cs-cz/dotnet/csharp/language-reference/builtin-types/integral-numeric-types",
        "https://learn.microsoft.com/cs-cz/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types",
        "https://learn.microsoft.com/cs-cz/dotnet/csharp/language-reference/builtin-types/char",
        "-Ukladani zapornych cisel:",
        "https://programovaci-ucebnice.g6.cz/ucebnice/UcebniceJazykaJava/7_Cela_cisla.xhtml"
    ))
    
@*
    

Více na...
    *@
<div class="sha text-center">Více informací: <a href="https://www.itnetwork.cz/csharp/zaklady/c-sharp-tutorial-cykly-for-while/">ItNetwork</a></div>



@* Redirect na jinou stránku *@
<li>
    <a asp-area=""
       asp-controller="Redirect"
       asp-action="Index"
       asp-route-url="https://www.itnetwork.cz/ms-office/excel/kontingencni-tabulky-v-aplikaci-excel">
        @*Zde změnit pouze odkaz*@
        Kontigenční tabulky</a>
</li>

    